# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97ce96dd8fe1d6b2b8107a8ba011c0ed75d4c653d460d1d65a9c71c035abdbf1059c20deb29a1c1375253522fc84c46c486ea4347d1b5e68e1afa0d4ba6044a6

test:
  secret_key_base: 95bd67039f846c1eb4548d82ca9fa0ec5feb60fe9ccff8ba1b6a4307464440d2b7d3d2bb2a931f84cd24c219c1ede9f7e1a7d2583364015c703b9f30c2f47416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
